#!/bin/bash
# Manual deployment guide for aws-assume-role function

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Deploy aws-assume-role Function Manually                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "The CLI token doesn't have deployment permissions."
echo "Here are your options:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Deploy via Supabase Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/prrmrukwmrjkdxcyzovd/functions"
echo "2. Click on 'aws-assume-role' function"
echo "3. Click 'Deploy' or 'Redeploy' button"
echo "4. Wait for deployment to complete"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: Get a Personal Access Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://supabase.com/dashboard/account/tokens"
echo "2. Click 'Generate new token'"
echo "3. Give it a name like 'AutoStack Deploy'"
echo "4. Copy the token (starts with 'sbp_')"
echo "5. Run: supabase login --token <your-token>"
echo "6. Run: supabase functions deploy aws-assume-role --project-ref prrmrukwmrjkdxcyzovd --no-verify-jwt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Use GitHub Actions (Automated)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Push your code to GitHub"
echo "2. Set up GitHub Actions with Supabase token"
echo "3. Auto-deploy on push"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "RECOMMENDED: Option 2 (Get Personal Access Token)"
echo "It's the fastest and gives you full control."
